version: '3'

services:
  nginx:
    build: ./nginx/
    ports:
      - 8081:80
    depends_on:
      - php
    volumes:
    - ./www/:/var/www/html
    restart: unless-stopped
  php:
    build: ./php/
    expose:
      - 9000
    volumes:
      - ./app/:/var/www/html
    restart: unless-stopped
  db:
    image: mariadb
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - ./mysql/config:/etc/mysql/conf.d
      - ./mysql/data:/var/lib/mysql
    ports:
      - 3306:3306